two_digit_number = input("Type a two digit number: ")
digit1 = int(two_digit_number[0])
digit2 = int(two_digit_number[1])
print("The calculation of first digit and second digit is: \n")
print(digit1 + digit2)
